const fs = require('fs');
const g = fs.readFileSync('游戏.html', 'utf8');
const has = (tag, pat, re) => {
  let ok = false;
  if (re) ok = re.test(g);
  else ok = g.includes(pat);
  console.log((ok ? '✓' : '✗ MISSING'), tag);
  return ok;
};
console.log('=== 前端优化九项核对 ===');
has('①a 任务横幅 mis_', "MIS_BANNER");
has('①b 危N徽章', 'hz-badge') || has('①b-alt 徽章', 'badge');
has('② 进度条条纹', 'repeating-linear-gradient');
has('③ lootIn 动画', '@keyframes lootIn');
has('④ 资源总览', 'function showResourceOverview');
has('⑤ Tab 角标', 'tabBadge') || has('⑤-alt badge span', 'data-badge');
has('⑥ 日志左色条', 'logline');
has('⑦ 交易清仓确认', '清仓');
has('⑧ bosco 空状态', 'misc_bosco');
has('⑨ 喝酒两击确认', 'confirmDrink') || has('⑨-alt 二次', '再次点击');
console.log('=== 手机修2 ===');
has('修2 chip 换行', '.mcard .chip{white-space:normal');
has('修2-alt min-width:0', 'min-width:0');
console.log('=== 减字专项 ===');
has('日志折叠', 'renderFullLog') && has('日志折叠fold', 'logFold');
has('战役摘要行', 'campSummary') || has('战役摘要-alt', 'campbar');
has('costChip 图标化', 'function costChip');
has('帮助页', 'function renderHelp');
console.log('=== 文案包 v1.4 键数对比 ===');
const w = fs.readFileSync('资料/游戏文案包.md', 'utf8');
const m = w.match(/```js([\s\S]*?)```/);
if (m) {
  const keys = [...m[1].matchAll(/^\s*([A-Za-z_][A-Za-z0-9_]*):/gm)].map(x => x[1]);
  console.log('文案包 v1.4 js块键数:', keys.length);
  const gm = g.match(/<script>([\s\S]*)<\/script>/);
  const gk = new Set([...gm[1].matchAll(/^\s*([A-Za-z_][A-Za-z0-9_]*):/gm)].map(x => x[1]));
  const missing = keys.filter(k => !gk.has(k));
  console.log('游戏缺键数:', missing.length);
  if (missing.length) console.log('缺键样例:', missing.slice(0, 30).join(', '));
} else console.log('文案包 js 块未匹配到');
